/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
var View=Laya.View;
var Dialog=Laya.Dialog;
var Scene=Laya.Scene;
var REG = Laya.ClassUtils.regClass;
export class game1UI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("game1");
	}
}
REG("ui.game1UI",game1UI);